[workspace]
resolver = "2"
members = [
  "contracts/*",
]

[workspace.dependencies]
soroban-sdk = "22.0.0"

# All contracts in this workspace
[workspace.metadata.contracts]
identity-registry = { path = "contracts/identity-registry" }
reputation-registry = { path = "contracts/reputation-registry" }
validation-registry = { path = "contracts/validation-registry" }

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true

# For more information about this profile see https://soroban.stellar.org/docs/basic-tutorials/logging#cargotoml-profile
[profile.release-with-logs]
inherits = "release"
debug-assertions = true
