export const CONTRACT_ADDRESSES = {
  VAULT_FACTORY: process.env.VAULT_FACTORY_ADDRESS || "",
  AGENT_REGISTRY: process.env.AGENT_REGISTRY_ADDRESS || "",
  REPUTATION_REGISTRY: process.env.REPUTATION_REGISTRY_ADDRESS || "",
  VALIDATION_REGISTRY: process.env.VALIDATION_REGISTRY_ADDRESS || "",
  USDC_SAC: process.env.USDC_SAC_ADDRESS || "",
};

export const VAULT_WASM_HASH = process.env.VAULT_WASM_HASH || "";
