export const VAULT_FACTORY_ADDRESS = process.env.NEXT_PUBLIC_VAULT_FACTORY_ADDRESS || "";
export const AGENT_REGISTRY_ADDRESS = process.env.NEXT_PUBLIC_AGENT_REGISTRY_ADDRESS || "";
export const REPUTATION_REGISTRY_ADDRESS = process.env.NEXT_PUBLIC_REPUTATION_REGISTRY_ADDRESS || "";
export const VALIDATION_REGISTRY_ADDRESS = process.env.NEXT_PUBLIC_VALIDATION_REGISTRY_ADDRESS || "";
export const USDC_SAC_ADDRESS = process.env.NEXT_PUBLIC_USDC_SAC_ADDRESS || "";
export const DEMO_VAULT_ADDRESS = "CAUQJXWHKFDZVXUL7ZLVAY5UCHOCZZ57IA3CYXMEGRBCS7EPIIQCKVTL";

// Agent signer public key (derived from mnemonic, mainnet)
export const AGENT_SIGNER_PUBLIC_KEY = "GDLCSUDUCBLY5Z727TAZ4ZLUTKYM2CC74FM77M3GJ7IA2BYEQRD6CRZ6";

// Facilitator public key (receives x402 payments on behalf of service)
export const FACILITATOR_PUBLIC_KEY = "GBMKTEEHXML52JTPM5USX4JONRVL32RVBQ6MWR4ZBTJHK6S63FB7JQTO";
